### ISSUE TITLE
Code style agreement

### ISSUE THREAD

**Issue by egordorichev** [matheusmortatti/pico8-emulator#108]
Since this project is no longer developed by a single person, it's really important to agree on the code style, as even small differences, as seen in #107 and #106 can really stand out. I will suggest my view here, please feel free to comment down below.

### My view on code style for C#

* 2-space sized **tabs**. The size doesn't matter too much, because it's pure visual rendering by the editor, but if you use spaces, and every person uses different amount of them, this is going to be trouble. Plus, I don't see any reasons behind using spaces?

* Brace style: I know this is going a bit against common C# standards, but IMO `1TBS` brace style (see `https://en.wikipedia.org/wiki/Indentation_style`) is much cleaner, allows to see more code on the same screen size and generally used almost everywhere.

* Field naming: this is a big one...
  + `public`: **always** `UpperCamelCase`. Note, that this applies to constants. Constants are always `UpperCamelCase`.
  + `private`:
    - `const`: `UpperCamelCase`
    - Otherwise: `camelCase`
  + Never use the `_` in field naming...

* And I think we all agree, that methods are always `UpperCamelCase`

**Comment by egordorichev** [comment]
I use Jetbrains Rider, and it's a piece of cake to reformat the code to any code style, really, not sure about Visual Studio tho.

**Comment by matheusmortatti** [comment]
Going through this in order:

- I'm currently using 4 spaces tabs. I like 2 spaces more actually, so I'll change it. However, I think your tabs are actual tabs right now, and that's problematic since each editor interprets tabs their own ways. What I do is translate tabs into actual spaces. It seems like in your editor you have 2-space *sized* tabs, while mine has 4-space sized tabs and github has who-knows-how-many sized tabs, so in each environment indentation will show differently. If you make your tabs translate to actual spaces, it'll be standardized across everything.

- Brace style is fine like that for me, your reasoning makes sense.

- I'm conflicted by this field naming convention. I don't like the fact that fields have the same naming pattern as methods. Also, I think that the closest we can get to the C# standard the better since it's easier for new people to understand since it's widely known. We should only change the standard where it makes sense (like with braces).

Let me know what you think!
